/*
Customer Orders & Revenue Analysis
SQL Business Case Study (PostgreSQL)

Goal:
Understand revenue, customer behavior, retention,
and growth patterns to support business decisions.
*/

-- 1. total revenue generated
select
    sum(order_amount) as total_revenue
from orders;

-- insight:
-- overall revenue generated by the business.


-- 2. total number of orders
select
    count(*) as total_orders
from orders;

-- insight:
-- shows overall transaction volume.


-- 3. average order value (aov)
select
    round(avg(order_amount), 2) as avg_order_value
from orders;

-- insight:
-- indicates how much customers spend per order on average.


-- 4. monthly revenue trend
select
    date_trunc('month', order_date) as month,
    sum(order_amount) as monthly_revenue
from orders
group by month
order by month;

-- insight:
-- helps spot growth trends and seasonality.


-- 5. top 10 customers by total spend
select
    c.customer_id,
    c.customer_name,
    sum(o.order_amount) as total_spent
from customers c
join orders o
    on c.customer_id = o.customer_id
group by c.customer_id, c.customer_name
order by total_spent desc
limit 10;

-- insight:
-- a small group of customers contributes a large share of revenue.


-- 6. repeat customers (more than one order)
select
    customer_id,
    count(*) as order_count
from orders
group by customer_id
having count(*) > 1
order by order_count desc;

-- insight:
-- identifies customers who return after their first purchase.


-- 7. revenue from repeat vs one-time customers
with customer_orders as (
    select
        customer_id,
        count(*) as order_count,
        sum(order_amount) as revenue
    from orders
    group by customer_id
)
select
    case
        when order_count > 1 then 'repeat_customer'
        else 'one_time_customer'
    end as customer_type,
    sum(revenue) as total_revenue
from customer_orders
group by customer_type;

-- insight:
-- repeat customers usually generate most of the revenue.


-- 8. payment method usage
select
    payment_method,
    count(*) as orders
from orders
group by payment_method
order by orders desc;

-- insight:
-- shows preferred payment options among customers.


-- 9. category-wise revenue contribution
select
    product_category,
    sum(quantity * price) as revenue
from order_items
group by product_category
order by revenue desc;

-- insight:
-- highlights which product categories drive sales.


-- 10. average days between orders per customer
with ordered_orders as (
    select
        customer_id,
        order_date,
        lag(order_date) over (
            partition by customer_id
            order by order_date
        ) as previous_order_date
    from orders
)
select
    customer_id,
    round(avg(order_date - previous_order_date), 2) as avg_days_between_orders
from ordered_orders
where previous_order_date is not null
group by customer_id
order by avg_days_between_orders;

-- insight:
-- helps understand how frequently customers place orders.


-- 11. customer retention rate by month
with monthly_customers as (
    select distinct
        customer_id,
        date_trunc('month', order_date) as month
    from orders
),
retained as (
    select
        m1.month,
        count(m1.customer_id) as retained_customers
    from monthly_customers m1
    join monthly_customers m2
        on m1.customer_id = m2.customer_id
       and m1.month = m2.month + interval '1 month'
    group by m1.month
),
total_customers as (
    select
        date_trunc('month', order_date) as month,
        count(distinct customer_id) as total_customers
    from orders
    group by month
)
select
    t.month,
    round(
        coalesce(r.retained_customers, 0)::numeric
        / t.total_customers * 100,
        2
    ) as retention_rate_percent
from total_customers t
left join retained r
    on t.month = r.month
order by t.month;

-- insight:
-- shows how well the business retains customers over time.


-- 12. month-over-month revenue growth
with monthly_revenue as (
    select
        date_trunc('month', order_date) as month,
        sum(order_amount) as revenue
    from orders
    group by month
)
select
    month,
    revenue,
    lag(revenue) over (order by month) as previous_month_revenue,
    round(
        (revenue - lag(revenue) over (order by month))
        / lag(revenue) over (order by month) * 100,
        2
    ) as mom_growth_percent
from monthly_revenue
order by month;

-- insight:
-- tracks revenue growth or slowdown month by month.


-- 13. customer lifetime value (simplified)
select
    customer_id,
    count(*) as total_orders,
    round(avg(order_amount), 2) as avg_order_value,
    sum(order_amount) as lifetime_value
from orders
group by customer_id
order by lifetime_value desc;

-- insight:
-- identifies customers with the highest long-term value.


-- 14. first vs repeat purchase revenue
select
    case
        when purchase_number = 1 then 'first_purchase'
        else 'repeat_purchase'
    end as purchase_type,
    sum(order_amount) as total_revenue
from (
    select
        customer_id,
        order_amount,
        row_number() over (
            partition by customer_id
            order by order_date
        ) as purchase_number
    from orders
) ranked
group by purchase_type;

-- insight:
-- shows how much revenue comes from new vs returning customers.


-- 15. pareto analysis (80/20 rule)
select
    customer_id,
    sum(order_amount) as revenue,
    round(
        sum(order_amount) * 100.0
        / sum(sum(order_amount)) over (),
        2
    ) as revenue_percent
from orders
group by customer_id
order by revenue desc;

-- insight:
-- confirms whether a small set of customers drives most revenue.


-- 16. funnel: customers by order count stage
select
    count(*) filter (where order_count = 1) as one_order_customers,
    count(*) filter (where order_count = 2) as two_order_customers,
    count(*) filter (where order_count >= 3) as three_plus_order_customers
from (
    select
        customer_id,
        count(*) as order_count
    from orders
    group by customer_id
) t;

-- insight:
-- shows drop-off from first purchase to repeat purchases.


-- 17. cohort-based retention (monthly)
with cohorts as (
    select
        customer_id,
        date_trunc('month', min(order_date)) as cohort_month
    from orders
    group by customer_id
),
activity as (
    select
        o.customer_id,
        c.cohort_month,
        date_trunc('month', o.order_date) as activity_month
    from orders o
    join cohorts c
        on o.customer_id = c.customer_id
)
select
    cohort_month,
    activity_month,
    count(distinct customer_id) as active_customers
from activity
group by cohort_month, activity_month
order by cohort_month, activity_month;

-- insight:
-- tracks how customer cohorts behave over time.


-- 18. top 3 customers per month
select
    month,
    customer_id,
    monthly_revenue
from (
    select
        date_trunc('month', order_date) as month,
        customer_id,
        sum(order_amount) as monthly_revenue,
        rank() over (
            partition by date_trunc('month', order_date)
            order by sum(order_amount) desc
        ) as rank
    from orders
    group by month, customer_id
) ranked
where rank <= 3;

-- insight:
-- identifies consistently high-spending customers.


-- 19. customers with increasing spend trend
with customer_monthly as (
    select
        customer_id,
        date_trunc('month', order_date) as month,
        sum(order_amount) as revenue
    from orders
    group by customer_id, month
),
revenue_trend as (
    select
        customer_id,
        month,
        revenue,
        revenue - lag(revenue) over (
            partition by customer_id
            order by month
        ) as revenue_change
    from customer_monthly
)
select distinct customer_id
from revenue_trend
where revenue_change > 0;

-- insight:
-- finds customers whose spending is increasing over time.


-- 20. revenue contribution by city
select
    c.city,
    sum(o.order_amount) as revenue,
    round(
        sum(o.order_amount) * 100.0
        / sum(sum(o.order_amount)) over (),
        2
    ) as revenue_percent
from customers c
join orders o
    on c.customer_id = o.customer_id
group by c.city
order by revenue desc;

-- insight:
-- helps identify top-performing cities.
